// Writes public/js/config.js from environment variables (Netlify) or a local .env file.
// Usage: node scripts/build-config.js
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envFile = path.join(root, '.env');

// Minimal .env loader for local development (KEY=value per line).
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, 'utf8').split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (match && !(match[1] in process.env)) {
      process.env[match[1]] = match[2].replace(/^['"]|['"]$/g, '');
    }
  }
}

const url = process.env.SUPABASE_URL || '';
const anonKey = process.env.SUPABASE_ANON_KEY || '';

// Refuse to ship a privileged key to the browser.
function isPrivilegedKey(key) {
  if (key.startsWith('sb_secret_')) return true;
  const parts = key.split('.');
  if (parts.length !== 3) return false;
  try {
    const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8'));
    return payload.role === 'service_role';
  } catch {
    return false;
  }
}

if (anonKey && isPrivilegedKey(anonKey)) {
  console.error('✖ SUPABASE_ANON_KEY looks like a service role / secret key. Use the public anon (publishable) key.');
  process.exit(1);
}

if (!url || !anonKey) {
  console.warn('⚠ SUPABASE_URL or SUPABASE_ANON_KEY is not set — the app will run in demo mode (browser-only storage).');
}

const output = `// Generated by scripts/build-config.js — do not edit or commit.
window.APP_CONFIG = ${JSON.stringify({ SUPABASE_URL: url, SUPABASE_ANON_KEY: anonKey }, null, 2)};
`;

fs.writeFileSync(path.join(root, 'public', 'js', 'config.js'), output);
console.log('✔ Wrote public/js/config.js');
